require_relative '../node_modules/react-native-permissions/scripts/setup'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'gdlite' do
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  permissions_path = '../node_modules/react-native-permissions/ios'

  config = use_native_modules!
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  # Eliminados pods de permisos innecesarios
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

# ✅ Mueve post_install fuera del target
post_install do |installer|
  react_native_post_install(
    installer,
    '../node_modules/react-native',
    :mac_catalyst_enabled => false
    # :ccache_enabled => true
  )
end
